[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "greeks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "scipy>=1.17.0",
    "numpy>=2.4.6"
]

[dependency-groups]
dev = [
    "marimo>=0.23.8",
    "plotly>=6.7.0",
    "polars>=1.41.1",
    "pandas>=3.0.3"
]

[tool.hatch.build.targets.wheel]
packages = ["src/greeks"]

[tool.deptry]
# see https://deptry.com/usage/#pep-621-dev-dependency-groups
pep621_dev_dependency_groups = ["dev"]
